-- Create Default Student Form
-- This script creates the default student registration form in the database
-- Run this script after creating the database schema

USE student_database;

-- Insert the default student form
INSERT INTO forms (
    form_id, 
    form_name, 
    form_description, 
    form_fields, 
    qr_code_data, 
    created_by, 
    is_active,
    created_at,
    updated_at
) VALUES (
    'default-student-form-001',
    'Default Student Registration Form',
    'This is a default form for student registration, created automatically on deployment.',
    JSON_ARRAY(
        JSON_OBJECT('key', 'pin_no', 'label', 'Pin No', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'course', 'label', 'Course', 'type', 'select', 'options', JSON_ARRAY(), 'required', true),
        JSON_OBJECT('key', 'current_year', 'label', 'Current Academic Year', 'type', 'select', 'options', JSON_ARRAY('1', '2', '3', '4'), 'required', true),
        JSON_OBJECT('key', 'current_semester', 'label', 'Current Semester', 'type', 'select', 'options', JSON_ARRAY('1', '2'), 'required', true),
        JSON_OBJECT('key', 'batch', 'label', 'Batch', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'branch', 'label', 'Branch', 'type', 'select', 'options', JSON_ARRAY(), 'required', true),
        JSON_OBJECT('key', 'stud_type', 'label', 'StudType', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'student_name', 'label', 'Student Name', 'type', 'text', 'required', true),
        JSON_OBJECT('key', 'student_status', 'label', 'Student Status', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'scholar_status', 'label', 'Scholar Status', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'student_mobile', 'label', 'Student Mobile Number', 'type', 'tel', 'required', false),
        JSON_OBJECT('key', 'parent_mobile1', 'label', 'Parent Mobile Number 1', 'type', 'tel', 'required', false),
        JSON_OBJECT('key', 'parent_mobile2', 'label', 'Parent Mobile Number 2', 'type', 'tel', 'required', false),
        JSON_OBJECT('key', 'caste', 'label', 'Caste', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'gender', 'label', 'M/F', 'type', 'select', 'options', JSON_ARRAY('M', 'F', 'Other'), 'required', false),
        JSON_OBJECT('key', 'father_name', 'label', 'Father Name', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'dob', 'label', 'DOB (Date of Birth - DD-MM-YYYY)', 'type', 'date', 'required', false),
        JSON_OBJECT('key', 'adhar_no', 'label', 'ADHAR No', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'admission_date', 'label', 'Admission Year (Ex: 09-Sep-2003)', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'admission_no', 'label', 'Admission No', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'student_address', 'label', 'Student Address', 'type', 'textarea', 'required', false),
        JSON_OBJECT('key', 'city_village', 'label', 'City/Village', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'mandal_name', 'label', 'Mandal Name', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'district', 'label', 'District', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'previous_college', 'label', 'Previous College Name', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'certificates_status', 'label', 'Certificate Status', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'student_photo', 'label', 'Student Photo', 'type', 'text', 'required', false),
        JSON_OBJECT('key', 'remarks', 'label', 'Remarks', 'type', 'textarea', 'required', false)
    ),
    '', -- QR code will be generated by the application
    (SELECT id FROM admins LIMIT 1), -- Use first admin as creator
    true,
    NOW(),
    NOW()
);

-- Update the QR code data (this will be done by the application)
-- The QR code URL will be: http://localhost:3000/form/default-student-form-001

SELECT 'Default student form created successfully!' as message;
